#!/bin/bash
isExistApp = `pgrep nginx`
if [[ -n  $isExistApp ]]; then
    service nginx stop        
fi

isExistNodeApp = `pgrep node`
if [[ -n  $isExistNodeApp ]]; then
    killall -9 node       
fi
